services:
  cyberbabasab-backend:
    container_name: cyberbabasab-backend
    image: cyberbabacool/cyberbabasab-backend:latest
    restart: unless-stopped
    env_file: .env
    ports:
      - "3001:3000"
    volumes:
      - cyberbabasab-config:/config
    networks:
      - cyberbabasab

  cyberbabasab-frontend:
    container_name: cyberbabasab-frontend
    image: cyberbabacool/cyberbabasab-frontend:latest
    restart: unless-stopped
    depends_on:
      - cyberbabasab-backend
    ports:
      - "8088:80"
    networks:
      - cyberbabasab

volumes:
  cyberbabasab-config:

networks:
  cyberbabasab:
    driver: bridge
