services:
  cyberbabasab-backend:
    container_name: cyberbabasab-backend
    image: cyberbabacool/cyberbabasab-backend:latest
    pull_policy: never
    restart: unless-stopped
    ports:
      - "3001:3000"
    networks:
      - cyberbabasab

  cyberbabasab-frontend:
    container_name: cyberbabasab-frontend
    image: cyberbabacool/cyberbabasab-frontend:latest
    restart: unless-stopped
    depends_on:
      - cyberbabasab-backend
    ports:
      - "8088:80"
    networks:
      - cyberbabasab

networks:
  cyberbabasab:
    driver: bridge
